// Generated by https://quicktype.io

export interface StudiosResponse {
    data: Studios;
}

export interface Studios {
    mal_id:      number;
    url:         string;
    titles:      Title[];
    images:      Images;
    favorites:   number;
    established: string;
    about:       string;
    count:       number;
    external:    External[];
}

export interface External {
    name: string;
    url:  string;
}

export interface Images {
    jpg: Jpg;
}

export interface Jpg {
    image_url: string;
}

export interface Title {
    type:  string;
    title: string;
}
